In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)
arr.shape

[1 2 3 4 5 6]


(6,)

In [8]:
arr.reshape(2,3)
arr.shape

(6,)

In [9]:
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
##identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr2)
# print(arr2[1:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [20]:
print(arr2[1:])

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [30]:
print(arr2[0:,2:4])
### here 0 represents the number of rows and 2:4 represents the range of columns 

[[ 3  4]
 [ 8  9]
 [13 14]]


In [32]:
arr3=np.array([1,2,3,4,5])

mean=np.mean(arr3)
std_dev=np.std(arr3)

print(mean, std_dev)

normalized_data=(arr3-mean)/std_dev
print(normalized_data)

3.0 1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
